### Credit Card Fraud Project

- Observation/Formatting/Splitting of Data
- Models: Logistic Regression and Neural Network
- Cross-Validation
- Imbalanced to Balanced Data Techniques
- Predictor Selection for LR


In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import KFold # import KFold
from sklearn.metrics import accuracy_score
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import RFE
from sklearn.neural_network import MLPClassifier 


%cd Downloads

[Errno 2] No such file or directory: 'Downloads'
/Users/dlaldea/Downloads


In [16]:
cr_f=pd.read_csv("creditcard.csv")

In [17]:
cr_f.head()
#Except for time the principal components are standarized mean=0 variance=1
cr_f.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  3.919560e-15  5.688174e-16 -8.769071e-15  2.782312e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean  -1.552563e-15  2.010663e-15 -1.694249e-15 -1.927028e-16 -3.137024e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

           ...                 V21           V22           V23           V24  \
count      ...        2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean       ...        1.537294e-16  7.959909e-16  5.367590e-16  4.458112e-15   
std        ...        7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min        ...       -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%        ...       -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%        ...       -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%        ...        1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max        ...        2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   1.453003e-15  1.699104e-15 -3.660161e-16 -1.206049e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [18]:

#get column labels and drop from matrix
labels = cr_f['Class']
#preserving only necessary columns 
cr_f.drop(['Class'], axis = 1, inplace = True)


In [19]:
#Split data in 80/20 to do the Feautre Selection
Train,Test,y_train, y_test=train_test_split(cr_f,labels, test_size=0.2,random_state=42)


### Logistic Regression- Full Model Accuracy and Cross Validation with Original Unbalanced Data

In [20]:

#Logistic Regression
log_reg=LogisticRegression()
#Logistic with entire data
log_reg.fit(Train, y_train)
pred_labels=log_reg.predict(Test)


In [21]:
#Get F1 score: For unbalanced data this is the metric. 
f1_score(pred_labels,y_test) #Accuracy of 64.59% with full unbalanced model

0.64596273291925477

In [22]:

np.random.seed(42)
acc=cross_val_score(log_reg,cr_f,labels, cv=4, scoring='f1')
print acc
print np.mean(acc)

[ 0.19932432  0.61538462  0.76190476  0.41025641]
0.496717527968


# Model Selection/ Feature Selection: 
- automatically select features in data that contribute most to the prediction variable. Done to reduce overfitting, improve accuracy and reduce training time. 

* RFE( Recursive Feature Elimination) works by recursively removing attributes and building a model on those attributes that remain. It uses the model accuracy to identify which attributes contribute the most to predict the target value. 


In [23]:
sm=SMOTE(random_state=42,ratio=1.0)
ov_train,ovy_train=sm.fit_sample(Train,y_train)
ov_train = pd.DataFrame(ov_train, columns = Train.columns)


### Feature Selection with OverSampled Data

In [24]:


rfe=RFE(log_reg,3)
rfe=rfe.fit(ov_train,ovy_train)

In [25]:
#Models
pred_ov=[]

for i in range(1,6):
    pred_ov.append(cr_f.columns[rfe.ranking_ <= i])

pred_ov



[Index([u'V4', u'V12', u'V14'], dtype='object'),
 Index([u'V4', u'V12', u'V14', u'V27'], dtype='object'),
 Index([u'V4', u'V12', u'V14', u'V27', u'V28'], dtype='object'),
 Index([u'V4', u'V10', u'V12', u'V14', u'V27', u'V28'], dtype='object'),
 Index([u'V4', u'V10', u'V12', u'V14', u'V17', u'V27', u'V28'], dtype='object')]

# Cross-Validation
### Oversampling witin Cross-Validation

In [26]:

    
def ML_CV(data,method, splits, over):
    
    """This method makes a k-Fold Cross Validation with Sampling Techniques for
    and tests the data for a specific method"""
    kf = KFold(n_splits=splits) # Define the split - into 2 folds 
    k=1
    #Create empty array to store results
    results=[]
    for train_index,test_index in kf.split(data):
    #Split into folds
        X_train,X_test= data.loc[train_index,:], data.loc[test_index,:]
        y_train,y_test=labels[train_index], labels[test_index]
    
    #Do oversampling or undersampling in Training Set
        if(over==True):
            sm=SMOTE(random_state=42,ratio=1.0)
            ov_train,y_train=sm.fit_sample(X_train,y_train)
            X_train = pd.DataFrame(ov_train, columns = X_train.columns)
        else: 
            rus=RandomUnderSampler(return_indices=True)
            ov_train,y_train,idx_resample=rus.fit_sample(X_train,y_train)
            X_train = pd.DataFrame(ov_train, columns = X_train.columns)
        
    #Do predictions using the Machine Learning Method on models and print results
        for i in range(0,len(pred_ov)):
        #Training models 
            model_train=X_train[pred_ov[i]]
            method.fit(model_train,y_train)
            pred_labels=method.predict(X_test[pred_ov[i]])
            results.append(round(accuracy_score(pred_labels,y_test),4))

    acc_results=np.array(results).reshape((4,5))
    print acc_results.mean(axis=0)


In [27]:
log_reg=LogisticRegression()
ML_CV(cr_f,log_reg,4,True)

[ 0.97945   0.979575  0.979875  0.98135   0.985725]


### Undersampling within CV

In [28]:
log_reg=LogisticRegression()
ML_CV(cr_f,log_reg,4,False)

[ 0.9707    0.9707    0.970425  0.97155   0.96915 ]


### Neural Network

In [11]:
#Neural Network with Original Data.
NN=MLPClassifier(activation="logistic",solver="adam")
NN.fit(Train,y_train)
accuracy_score(NN.predict(Test),y_test)

 


0.99827955479091324

In [ ]:
#Neural Network with Oversampled Data
NN=MLPClassifier(activation="logistic",solver="adam")
ML_CV(cr_f,NN,4,True)
print NN.get_params()



[ 0.97985   0.982075  0.984425  0.98765   0.993275]

In [ ]:
#Neural Network with Undersampled Data 
NN=MLPClassifier(activation="logistic",solver="adam")
ML_CV(cr_f,NN,4,False)


[ 0.96835   0.968375  0.966675  0.9704    0.971025]